
export const GET_INFO_SUCCESS = "GET_INFO_SUCCESS";
export const GET_INFO_FAIL = "GET_INFO_FAIL";
export const GET_ALL_INFO_SUCCESS = "GET_ALL_INFO_SUCCESS";
export const GET_ALL_INFO_FAIL = "GET_ALL_INFO_FAIL";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_FAIL = "POST_DATA_FAIL";
export const GET_ALL_VIDEO_INFO_SUCCESS = "GET_ALL_VIDEO_INFO_SUCCESS";
export const GET_ALL_VIDEO_INFO_FAIL = "GET_ALL_VIDEO_INFO_FAIL";
